- name: variables to print
  hosts: web
  vars:
    COURSE: " Devops with AWS"
    DURATION: "120HRS"
    TRAINER: "siva kumar reddy"
  tasks:
  - name: print the information
    ansible.buildin.debug:
      msg: "Hi, I am learning {{ COURSE }}, Duartion is: {{DURATION }}, trainer: {{ TRAINER}}"






    