
- name: variables to prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
    private: false # not creditential
  - name: DURATION  
    prompt: please enter the duration name
    private: false # not creditential
  - name: TRAINER  
    prompt: please enter the trainer name
    private: false # not creditential
  tasks:
  - name: print the course information
    ansible.builtin.debug:
    msg: "Hi I am learning {{ COURSE }}," duration is {{ DURATION }}, trainer {{ TRAINER }}"

   
