- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg:  "hello {{ course | default('ansible') }}"

  
  
  - name: convert to uppercase
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: " {{ greeting | upper }}"




  - name: convert to lowercase
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: " {{ greeting | lower }}"
  

  - name: get the unique values
    vars:
      numbers: [ 20 ,40,23,100,145,20, 20,23,127,127]
    ansible.builtin.debug:
      msg: " {{ numbers | unique }}"  
  




                     
  
                                 



